/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;


/**
 *
 * @author bispo
 */
public class JDlgUsuario_ed extends javax.swing.JDialog {

    /**
     * Creates new form jDlgUsuario
     */
    private MaskFormatter mascaraCpf, mascaraData;
   
    public JDlgUsuario_ed(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Usuario");
        setLocationRelativeTo(null);
        Util.habilitar(false, jCboNivel_ed, jTxtApelido_ed, jTxtCodigo_ed, jTxtNome_ed, jBtnAlterar_ed,
 jBtnCancelar_ed, jBtnConfirmar_ed, jBtnExcluir_ed, jBtnIncluir_ed, jBtnPesquisar_ed, jFmtCPF_ed, jFmtDataNasc_ed);
        try {
            mascaraCpf = new MaskFormatter("###.###.###-##");
            mascaraData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuario_ed.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFmtCPF_ed.setFormatterFactory(new DefaultFormatterFactory(mascaraCpf));
        jFmtDataNasc_ed.setFormatterFactory(new DefaultFormatterFactory(mascaraData));
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblCodigo = new javax.swing.JLabel();
        jLblNome = new javax.swing.JLabel();
        jLblApelido = new javax.swing.JLabel();
        JLblCPF = new javax.swing.JLabel();
        JLblDataNasc = new javax.swing.JLabel();
        JLblSenha = new javax.swing.JLabel();
        JLblNivel = new javax.swing.JLabel();
        jTxtCodigo_ed = new javax.swing.JTextField();
        jTxtNome_ed = new javax.swing.JTextField();
        jTxtApelido_ed = new javax.swing.JTextField();
        jFmtCPF_ed = new javax.swing.JFormattedTextField();
        jFmtDataNasc_ed = new javax.swing.JFormattedTextField();
        jPwfSenha_ed = new javax.swing.JPasswordField();
        jCboNivel_ed = new javax.swing.JComboBox<>();
        jChbAtivo_ed = new javax.swing.JCheckBox();
        jBtnIncluir_ed = new javax.swing.JButton();
        jBtnAlterar_ed = new javax.swing.JButton();
        jBtnExcluir_ed = new javax.swing.JButton();
        jBtnConfirmar_ed = new javax.swing.JButton();
        jBtnCancelar_ed = new javax.swing.JButton();
        jBtnPesquisar_ed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblCodigo.setText("Código");

        jLblNome.setText("Nome");

        jLblApelido.setText("Apelido");

        JLblCPF.setText("CPF");

        JLblDataNasc.setText("Data de Nascimento");

        JLblSenha.setText("Senha");

        JLblNivel.setText("Nível");

        jTxtCodigo_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigo_edActionPerformed(evt);
            }
        });

        jFmtDataNasc_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtDataNasc_edActionPerformed(evt);
            }
        });

        jCboNivel_ed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jChbAtivo_ed.setText("Ativo");

        jBtnIncluir_ed.setText("Incluir");
        jBtnIncluir_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_edActionPerformed(evt);
            }
        });

        jBtnAlterar_ed.setText("Alterar");
        jBtnAlterar_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_edActionPerformed(evt);
            }
        });

        jBtnExcluir_ed.setText("Excluir");
        jBtnExcluir_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_edActionPerformed(evt);
            }
        });

        jBtnConfirmar_ed.setText("Confirmar");
        jBtnConfirmar_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmar_edActionPerformed(evt);
            }
        });

        jBtnCancelar_ed.setText("Cancelar");
        jBtnCancelar_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_edActionPerformed(evt);
            }
        });

        jBtnPesquisar_ed.setText("Pesquisar");
        jBtnPesquisar_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisar_edActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPwfSenha_ed)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLblSenha)
                                .addGap(246, 246, 246)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLblNivel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCboNivel_ed, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jChbAtivo_ed))))
                    .addComponent(jTxtNome_ed)
                    .addComponent(jTxtApelido_ed)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblApelido)
                            .addComponent(jLblNome)
                            .addComponent(jLblCodigo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnIncluir_ed)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnAlterar_ed)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnExcluir_ed)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnConfirmar_ed)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnCancelar_ed)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnPesquisar_ed))
                            .addComponent(jTxtCodigo_ed, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jFmtCPF_ed, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(199, 199, 199))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JLblCPF)
                                        .addGap(330, 330, 330)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblDataNasc)
                                    .addComponent(jFmtDataNasc_ed, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)))
                        .addGap(47, 47, 47)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodigo_ed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNome_ed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblApelido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtApelido_ed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblCPF)
                    .addComponent(JLblDataNasc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtCPF_ed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtDataNasc_ed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblSenha)
                    .addComponent(JLblNivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwfSenha_ed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboNivel_ed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbAtivo_ed))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir_ed)
                    .addComponent(jBtnConfirmar_ed)
                    .addComponent(jBtnAlterar_ed)
                    .addComponent(jBtnExcluir_ed)
                    .addComponent(jBtnCancelar_ed)
                    .addComponent(jBtnPesquisar_ed))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluir_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_edActionPerformed
        Util.habilitar(true, jCboNivel_ed, jTxtApelido_ed, jTxtCodigo_ed, jBtnCancelar_ed, jTxtNome_ed, jFmtCPF_ed, jFmtDataNasc_ed, jBtnConfirmar_ed);
        Util.habilitar(false, jBtnAlterar_ed, jBtnExcluir_ed, jBtnIncluir_ed, jBtnPesquisar_ed);
    }//GEN-LAST:event_jBtnIncluir_edActionPerformed

    private void jBtnAlterar_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_edActionPerformed
        Util.limpar(jCboNivel_ed, jTxtApelido_ed, jTxtCodigo_ed, jTxtNome_ed, jBtnAlterar_ed, jBtnCancelar_ed, jBtnConfirmar_ed, jBtnExcluir_ed, jBtnIncluir_ed, jBtnPesquisar_ed, jFmtCPF_ed, jFmtDataNasc_ed);
        Util.habilitar(true, jCboNivel_ed, jTxtApelido_ed, jTxtCodigo_ed, jTxtNome_ed, jBtnCancelar_ed, jBtnConfirmar_ed, jFmtCPF_ed, jFmtDataNasc_ed);
        Util.habilitar(false, jBtnIncluir_ed, jBtnAlterar_ed, jBtnExcluir_ed, jBtnPesquisar_ed);
    }//GEN-LAST:event_jBtnAlterar_edActionPerformed

    private void jBtnExcluir_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_edActionPerformed
        JOptionPane.showMessageDialog(null, "Exclusão");
          int resp = JOptionPane.showConfirmDialog(null, "Confirma Exclusão", "Deletar Registro", JOptionPane.YES_NO_OPTION);
          if (resp == JOptionPane.YES_OPTION){
              Util.limpar(jCboNivel_ed, jTxtApelido_ed, jTxtCodigo_ed, jTxtNome_ed, jBtnAlterar_ed, jBtnCancelar_ed, jBtnConfirmar_ed, jBtnExcluir_ed, jBtnIncluir_ed, jBtnPesquisar_ed, jFmtCPF_ed, jFmtDataNasc_ed);
          }
    }//GEN-LAST:event_jBtnExcluir_edActionPerformed

    private void jBtnConfirmar_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmar_edActionPerformed
        Util.habilitar(false, jChbAtivo_ed, jCboNivel_ed, jTxtApelido_ed, jTxtCodigo_ed, jTxtNome_ed, jBtnCancelar_ed, jBtnConfirmar_ed, jFmtCPF_ed, jFmtDataNasc_ed);
        Util.habilitar(true, jBtnIncluir_ed, jBtnAlterar_ed, jBtnExcluir_ed, jBtnPesquisar_ed);
        JOptionPane.showMessageDialog(null, "Usuário Cadastrado!");
        Util.limpar(jChbAtivo_ed, jCboNivel_ed, jTxtApelido_ed, jTxtCodigo_ed, jTxtNome_ed, jBtnAlterar_ed, jBtnCancelar_ed, jBtnConfirmar_ed, jBtnExcluir_ed, jBtnIncluir_ed, jBtnPesquisar_ed, jFmtCPF_ed, jFmtDataNasc_ed);
    }//GEN-LAST:event_jBtnConfirmar_edActionPerformed

    private void jBtnCancelar_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_edActionPerformed
        Util.habilitar(false, jChbAtivo_ed, jCboNivel_ed, jTxtApelido_ed, jTxtCodigo_ed, jTxtNome_ed, jBtnCancelar_ed, jBtnConfirmar_ed, jFmtCPF_ed, jFmtDataNasc_ed);
        Util.habilitar(true, jBtnIncluir_ed, jBtnAlterar_ed, jBtnExcluir_ed, jBtnPesquisar_ed);
    }//GEN-LAST:event_jBtnCancelar_edActionPerformed

    private void jBtnPesquisar_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisar_edActionPerformed
        JDlgPesquisarUsuario jDlgPesquisarUsuario = new JDlgPesquisarUsuario(null, true);
        jDlgPesquisarUsuario.setVisible(true);
    }//GEN-LAST:event_jBtnPesquisar_edActionPerformed

    private void jTxtCodigo_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigo_edActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigo_edActionPerformed

    private void jFmtDataNasc_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtDataNasc_edActionPerformed
        
    }//GEN-LAST:event_jFmtDataNasc_edActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuario_ed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuario_ed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuario_ed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuario_ed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuario_ed dialog = new JDlgUsuario_ed(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLblCPF;
    private javax.swing.JLabel JLblDataNasc;
    private javax.swing.JLabel JLblNivel;
    private javax.swing.JLabel JLblSenha;
    private javax.swing.JButton jBtnAlterar_ed;
    private javax.swing.JButton jBtnCancelar_ed;
    private javax.swing.JButton jBtnConfirmar_ed;
    private javax.swing.JButton jBtnExcluir_ed;
    private javax.swing.JButton jBtnIncluir_ed;
    private javax.swing.JButton jBtnPesquisar_ed;
    private javax.swing.JComboBox<String> jCboNivel_ed;
    private javax.swing.JCheckBox jChbAtivo_ed;
    private javax.swing.JFormattedTextField jFmtCPF_ed;
    private javax.swing.JFormattedTextField jFmtDataNasc_ed;
    private javax.swing.JLabel jLblApelido;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JPasswordField jPwfSenha_ed;
    private javax.swing.JTextField jTxtApelido_ed;
    private javax.swing.JTextField jTxtCodigo_ed;
    private javax.swing.JTextField jTxtNome_ed;
    // End of variables declaration//GEN-END:variables
}
