/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import tools.Util;
/**
 *
 * @author Erickson
 */
public class JDlgVenda_ed extends javax.swing.JDialog {

    /**
     * Creates new form jDglVenda
     * @param parent
     * @param modal
     */
    public JDlgVenda_ed(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Venda");
        setLocationRelativeTo(null);
        Util.habilitar(false, jTxtCodigoCliente_ed, jTxtCodigoFuncionario_ed, jTxtCodigo_ed, 
    jTxtData_ed, jTxtTotal_ed, jBtnCancelar_ed, jBtnConfirmar_ed, 
    jBtnExcluir_ed, jBtnIncluir_ed, jBtnPesquisar_ed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnIncluir_ed = new javax.swing.JButton();
        jBtnAlterar_ed = new javax.swing.JButton();
        jBtnExcluir_ed1 = new javax.swing.JButton();
        jLblCodigo = new javax.swing.JLabel();
        jTxtCodigo_ed = new javax.swing.JTextField();
        jLblCodigoCliente = new javax.swing.JLabel();
        jLblCodigoFuncionario = new javax.swing.JLabel();
        jTxtCodigoFuncionario_ed = new javax.swing.JTextField();
        jTxtCodigoCliente_ed = new javax.swing.JTextField();
        jLblData = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtData_ed = new javax.swing.JTextField();
        jLblTotal = new javax.swing.JLabel();
        jTxtTotal_ed = new javax.swing.JTextField();
        jBtnIncluir_ed1 = new javax.swing.JButton();
        jBtnAlterar_ed1 = new javax.swing.JButton();
        jBtnExcluir_ed = new javax.swing.JButton();
        jBtnConfirmar_ed = new javax.swing.JButton();
        jBtnPesquisar_ed = new javax.swing.JButton();
        jBtnCancelar_ed = new javax.swing.JButton();

        jBtnIncluir_ed.setText("Incluir");
        jBtnIncluir_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_edActionPerformed(evt);
            }
        });

        jBtnAlterar_ed.setText("Alterar");
        jBtnAlterar_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_edActionPerformed(evt);
            }
        });

        jBtnExcluir_ed1.setText("Excluir");
        jBtnExcluir_ed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_ed1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblCodigo.setText("Codigo da Venda");

        jTxtCodigo_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigo_edActionPerformed(evt);
            }
        });

        jLblCodigoCliente.setText("Código Cliente");

        jLblCodigoFuncionario.setText("Codigo Funcionario");

        jTxtCodigoCliente_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoCliente_edActionPerformed(evt);
            }
        });

        jLblData.setText("Data");

        jLblTotal.setText("Total R$:");

        jBtnIncluir_ed1.setText("Incluir");
        jBtnIncluir_ed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_ed1ActionPerformed(evt);
            }
        });

        jBtnAlterar_ed1.setText("Alterar");
        jBtnAlterar_ed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_ed1ActionPerformed(evt);
            }
        });

        jBtnExcluir_ed.setText("Excluir");
        jBtnExcluir_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_edActionPerformed(evt);
            }
        });

        jBtnConfirmar_ed.setText("Confirmar");
        jBtnConfirmar_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmar_edActionPerformed(evt);
            }
        });

        jBtnPesquisar_ed.setText("Pesquisar");
        jBtnPesquisar_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisar_edActionPerformed(evt);
            }
        });

        jBtnCancelar_ed.setText("Cancelar");
        jBtnCancelar_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_edActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblCodigo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblCodigoCliente)
                                        .addGap(96, 96, 96))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtCodigoCliente_ed)
                                        .addGap(24, 24, 24)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLblData)
                                        .addComponent(jTxtData_ed, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtCodigo_ed, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLblTotal)
                                .addComponent(jTxtCodigoFuncionario_ed, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLblCodigoFuncionario)
                                .addComponent(jTxtTotal_ed, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBtnIncluir_ed1)
                                    .addGap(54, 54, 54))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jBtnConfirmar_ed)
                                    .addGap(35, 35, 35)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jBtnAlterar_ed1)
                                .addComponent(jBtnPesquisar_ed))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jBtnCancelar_ed)
                                .addComponent(jBtnExcluir_ed)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodigo_ed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCodigoCliente)
                    .addComponent(jLblCodigoFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCodigoFuncionario_ed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCodigoCliente_ed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblData)
                    .addComponent(jLblTotal))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtData_ed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTotal_ed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir_ed1)
                    .addComponent(jBtnAlterar_ed1)
                    .addComponent(jBtnExcluir_ed))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnConfirmar_ed)
                            .addComponent(jBtnPesquisar_ed)
                            .addComponent(jBtnCancelar_ed))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCodigo_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigo_edActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigo_edActionPerformed

    private void jTxtCodigoCliente_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoCliente_edActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigoCliente_edActionPerformed

    private void jBtnIncluir_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_edActionPerformed
       Util.habilitar(true, jTxtCodigoCliente_ed, jTxtCodigoFuncionario_ed, jTxtCodigo_ed, 
    jTxtData_ed, jTxtTotal_ed, jBtnCancelar_ed, jBtnConfirmar_ed);
    Util.habilitar(false, jBtnIncluir_ed, jBtnAlterar_ed, jBtnExcluir_ed, jBtnPesquisar_ed);
    }//GEN-LAST:event_jBtnIncluir_edActionPerformed

    private void jBtnIncluir_ed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_ed1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnIncluir_ed1ActionPerformed

    private void jBtnAlterar_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_edActionPerformed
        Util.habilitar(true, jTxtCodigoCliente_ed, jTxtCodigoFuncionario_ed, jTxtCodigo_ed, 
    jTxtData_ed, jTxtTotal_ed, jBtnCancelar_ed, jBtnConfirmar_ed);
    Util.habilitar(false, jBtnIncluir_ed, jBtnAlterar_ed, jBtnExcluir_ed, jBtnPesquisar_ed);
    }//GEN-LAST:event_jBtnAlterar_edActionPerformed

    private void jBtnAlterar_ed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_ed1ActionPerformed
        Util.habilitar(true, jTxtCodigoCliente_ed, jTxtCodigoFuncionario_ed, jTxtCodigo_ed, 
    jTxtData_ed, jTxtTotal_ed, jBtnCancelar_ed, jBtnConfirmar_ed);
    Util.habilitar(false, jBtnIncluir_ed, jBtnAlterar_ed, jBtnExcluir_ed, jBtnPesquisar_ed);
    }//GEN-LAST:event_jBtnAlterar_ed1ActionPerformed

    private void jBtnExcluir_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_edActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "Confirma Exclusão", "Deletar Registro", JOptionPane.YES_NO_OPTION);
    if (resp == JOptionPane.YES_OPTION) {   
        Util.limpar(jTxtCodigoCliente_ed, jTxtCodigoFuncionario_ed, jTxtCodigo_ed, 
        jTxtData_ed, jTxtTotal_ed, jBtnCancelar_ed, jBtnConfirmar_ed, 
        jBtnExcluir_ed, jBtnIncluir_ed, jBtnPesquisar_ed);
    }
    }//GEN-LAST:event_jBtnExcluir_edActionPerformed

    private void jBtnExcluir_ed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_ed1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnExcluir_ed1ActionPerformed

    private void jBtnConfirmar_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmar_edActionPerformed
       Util.habilitar(false, jTxtCodigoCliente_ed, jTxtCodigoFuncionario_ed, jTxtCodigo_ed, 
    jTxtData_ed, jTxtTotal_ed, jBtnCancelar_ed, jBtnConfirmar_ed);
    Util.habilitar(true, jBtnIncluir_ed, jBtnAlterar_ed, jBtnExcluir_ed, jBtnPesquisar_ed);
    JOptionPane.showMessageDialog(null, "Registro Confirmado!");
    Util.limpar(jTxtCodigoCliente_ed, jTxtCodigoFuncionario_ed, jTxtCodigo_ed, 
    jTxtData_ed, jTxtTotal_ed, jBtnCancelar_ed, jBtnConfirmar_ed, 
    jBtnExcluir_ed, jBtnIncluir_ed, jBtnPesquisar_ed);
    }//GEN-LAST:event_jBtnConfirmar_edActionPerformed

    private void jBtnPesquisar_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisar_edActionPerformed
        JDlgPesquisarVenda jDlgPesquisarVenda = new JDlgPesquisarVenda(null, true);
        jDlgPesquisarVenda.setVisible(true);
    }//GEN-LAST:event_jBtnPesquisar_edActionPerformed

    private void jBtnCancelar_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_edActionPerformed
        Util.habilitar(false, jTxtCodigoCliente_ed, jTxtCodigoFuncionario_ed, jTxtCodigo_ed, 
    jTxtData_ed, jTxtTotal_ed, jBtnCancelar_ed, jBtnConfirmar_ed);
    Util.habilitar(true, jBtnIncluir_ed, jBtnAlterar_ed, jBtnExcluir_ed, jBtnPesquisar_ed);
    }//GEN-LAST:event_jBtnCancelar_edActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda_ed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda_ed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda_ed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda_ed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVenda_ed dialog = new JDlgVenda_ed(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar_ed;
    private javax.swing.JButton jBtnAlterar_ed1;
    private javax.swing.JButton jBtnCancelar_ed;
    private javax.swing.JButton jBtnConfirmar_ed;
    private javax.swing.JButton jBtnExcluir_ed;
    private javax.swing.JButton jBtnExcluir_ed1;
    private javax.swing.JButton jBtnIncluir_ed;
    private javax.swing.JButton jBtnIncluir_ed1;
    private javax.swing.JButton jBtnPesquisar_ed;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblCodigoCliente;
    private javax.swing.JLabel jLblCodigoFuncionario;
    private javax.swing.JLabel jLblData;
    private javax.swing.JLabel jLblTotal;
    private javax.swing.JTextField jTxtCodigoCliente_ed;
    private javax.swing.JTextField jTxtCodigoFuncionario_ed;
    private javax.swing.JTextField jTxtCodigo_ed;
    private javax.swing.JTextField jTxtData_ed;
    private javax.swing.JTextField jTxtTotal_ed;
    // End of variables declaration//GEN-END:variables
}
